/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.FornecedorDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regrasDeNegocios.Fornecedor;

/**
 *
 * @author ANINHA
 */
public class FormFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form FormFornecedor
     */
    public FormFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencherTabela();

        btAtalizar.setVisible(false);
        btEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paineGeralFornecedor = new javax.swing.JTabbedPane();
        painelListar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        edPesquisaNome = new javax.swing.JTextField();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        painelCadastrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        edTelefone = new javax.swing.JTextField();
        edMaterial_Fornecido = new javax.swing.JTextField();
        edEmail = new javax.swing.JTextField();
        edRua = new javax.swing.JTextField();
        edID = new javax.swing.JTextField();
        lbCadastrar = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btAtalizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        edCNPJ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edCidade1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        paineGeralFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        painelListar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nome:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CNPJ", "Telefone", "E-mail", "Endereço", "Material Fornecido", "Cidade", "Bairro"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        edPesquisaNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelListarLayout = new javax.swing.GroupLayout(painelListar);
        painelListar.setLayout(painelListarLayout);
        painelListarLayout.setHorizontalGroup(
            painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelListarLayout.createSequentialGroup()
                        .addGroup(painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(painelListarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 88, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(painelListarLayout.createSequentialGroup()
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        painelListarLayout.setVerticalGroup(
            painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelListarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        paineGeralFornecedor.addTab("Lista De Fornecedores", painelListar);

        painelCadastrar.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");
        painelCadastrar.add(jLabel1);
        jLabel1.setBounds(30, 90, 38, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CNPJ:");
        painelCadastrar.add(jLabel2);
        jLabel2.setBounds(30, 120, 40, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Telefone:");
        painelCadastrar.add(jLabel3);
        jLabel3.setBounds(250, 120, 56, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("E-mail:");
        painelCadastrar.add(jLabel4);
        jLabel4.setBounds(40, 270, 40, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Endereço:");
        painelCadastrar.add(jLabel5);
        jLabel5.setBounds(20, 160, 60, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Material Fornecido:");
        painelCadastrar.add(jLabel6);
        jLabel6.setBounds(10, 240, 116, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ID:");
        painelCadastrar.add(jLabel7);
        jLabel7.setBounds(40, 50, 18, 15);
        painelCadastrar.add(edNome);
        edNome.setBounds(80, 80, 410, 25);
        painelCadastrar.add(edTelefone);
        edTelefone.setBounds(320, 120, 150, 25);
        painelCadastrar.add(edMaterial_Fornecido);
        edMaterial_Fornecido.setBounds(130, 230, 360, 25);
        painelCadastrar.add(edEmail);
        edEmail.setBounds(90, 270, 400, 25);
        painelCadastrar.add(edRua);
        edRua.setBounds(90, 160, 210, 25);

        edID.setEditable(false);
        painelCadastrar.add(edID);
        edID.setBounds(70, 50, 100, 25);

        lbCadastrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbCadastrar.setText("Cadastrar Fornecedor");
        painelCadastrar.add(lbCadastrar);
        lbCadastrar.setBounds(150, 10, 270, 29);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        painelCadastrar.add(btSalvar);
        btSalvar.setBounds(90, 350, 100, 40);

        btAtalizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAtalizar.setText("Atalizar");
        btAtalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtalizarActionPerformed(evt);
            }
        });
        painelCadastrar.add(btAtalizar);
        btAtalizar.setBounds(230, 350, 100, 40);

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        painelCadastrar.add(btCancelar);
        btCancelar.setBounds(360, 350, 100, 40);

        edCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCNPJActionPerformed(evt);
            }
        });
        painelCadastrar.add(edCNPJ);
        edCNPJ.setBounds(80, 120, 150, 20);

        jLabel9.setText("CIDADE:");
        painelCadastrar.add(jLabel9);
        jLabel9.setBounds(260, 200, 50, 14);

        edBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edBairroActionPerformed(evt);
            }
        });
        painelCadastrar.add(edBairro);
        edBairro.setBounds(90, 200, 150, 20);

        jLabel10.setText("BAIRRO:");
        painelCadastrar.add(jLabel10);
        jLabel10.setBounds(30, 200, 43, 14);
        painelCadastrar.add(edCidade1);
        edCidade1.setBounds(310, 200, 110, 20);

        paineGeralFornecedor.addTab("Cadastrar", painelCadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paineGeralFornecedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(paineGeralFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Fornecedor f = new Fornecedor();
        f.setNome_for(edNome.getText());
        f.setCnpj_for(edCNPJ.getText());
        f.setEmail_for(edEmail.getText());
        f.setTelefone_for(edTelefone.getText());
        f.setCidade_for(edCidade1.getText());
        f.setBairro_for(edBairro.getText());
        f.setRua_for(edRua.getText());
        f.setMaterial_fornecido(edMaterial_Fornecido.getText());
        
        FornecedorDao fDao = new FornecedorDao();
        fDao.cadastrar(f);
        preencherTabela();
        btCancelarActionPerformed(evt);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
       edID.setText(null);
       edNome.setText(null);
       edCNPJ.setText(null);
       edTelefone.setText(null);
       edEmail.setText(null);
       edCidade1.setText(null);
       edBairro.setText(null);
       edRua.setText(null);
       edMaterial_Fornecido.setText(null);
       paineGeralFornecedor.setSelectedIndex(0);
    
       btSalvar.setVisible(true);
       btAtalizar.setVisible(false);
       
       lbCadastrar.setVisible(true);
       btEditar.setVisible(false);
       
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        btCancelarActionPerformed(evt);
        paineGeralFornecedor.setSelectedIndex(1);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
       int linhaTabela = tabela.getSelectedRow();
       if(linhaTabela >= 0){
       edID.setText(tabela.getValueAt(linhaTabela, 0).toString());
       edNome.setText(tabela.getValueAt(linhaTabela, 1).toString());
       edCNPJ.setText(tabela.getValueAt(linhaTabela, 2).toString());
       edTelefone.setText(tabela.getValueAt(linhaTabela, 3).toString());
       edEmail.setText(tabela.getValueAt(linhaTabela, 4).toString());
       edRua.setText(tabela.getValueAt(linhaTabela, 5).toString());
       edCidade1.setText(tabela.getValueAt(linhaTabela, 6).toString());
       edBairro.setText(tabela.getValueAt(linhaTabela, 7).toString());
       edMaterial_Fornecido.setText(tabela.getValueAt(linhaTabela, 8).toString());
       paineGeralFornecedor.setSelectedIndex(1);
       
       btSalvar.setVisible(false);
       btAtalizar.setVisible(true);
       
       lbCadastrar.setVisible(false);
       btEditar.setVisible(true);
       }else{
           JOptionPane.showMessageDialog(null,"Selecione um Fornecedor Na tabela");
       }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linhaTabela = tabela.getSelectedRow();
        if(linhaTabela >= 0){
            Fornecedor f = new Fornecedor();
            f.setId_fornecedor(Integer.parseInt(tabela.getValueAt(linhaTabela, 0).toString()));
            FornecedorDao fDao = new FornecedorDao();
            fDao.excluir(f);
            preencherTabela();
        }else{
           JOptionPane.showMessageDialog(null,"Selecione um Fornecedor Na tabela");
       }
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAtalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtalizarActionPerformed
    
    }//GEN-LAST:event_btAtalizarActionPerformed

    private void edCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCNPJActionPerformed

    private void edBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edBairroActionPerformed

   public void preencherTabela(){
       FornecedorDao fDao = new FornecedorDao();
       List<Fornecedor> lista = fDao.listarTodos();
       DefaultTableModel modeloTabela = (DefaultTableModel)tabela.getModel();
       modeloTabela.setRowCount(0);
       for(Fornecedor f : lista){
           modeloTabela.addRow(new Object[]{f.getId_fornecedor(), f.getNome_for(), f.getCnpj_for(), f.getTelefone_for(), f.getEmail_for(), f.getRua_for(), f.getMaterial_fornecido(), f.getCidade_for(), f.getBairro_for()});
       }
       
   }
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormFornecedor dialog = new FormFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtalizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField edBairro;
    private javax.swing.JTextField edCNPJ;
    private javax.swing.JTextField edCidade1;
    private javax.swing.JTextField edEmail;
    private javax.swing.JTextField edID;
    private javax.swing.JTextField edMaterial_Fornecido;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edPesquisaNome;
    private javax.swing.JTextField edRua;
    private javax.swing.JTextField edTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCadastrar;
    private javax.swing.JTabbedPane paineGeralFornecedor;
    private javax.swing.JPanel painelCadastrar;
    private javax.swing.JPanel painelListar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
